pull_request_rules:

  # ===============================================================================
  # DEPENDABOT
  # ===============================================================================

  - name: Automatic Merge for Dependabot Minor Version Pull Requests
    conditions:
      - -draft
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success='Analyze (javascript)'
    actions:
      review:
        type: APPROVE
        message: Automatically approving dependabot pull request
      merge:
        method: merge


  # ===============================================================================
  # AUTHOR
  # ===============================================================================

  - name: Auto-Assign Author
    conditions:
      - "#assignee=0"
    actions:
      assign:
        add_users:
          - "{{author}}"


  # ===============================================================================
  # LABELS
  # ===============================================================================
  # Automatically add labels when PRs match certain patterns
  #
  # NOTE:
  # - single quotes for regex to avoid accidental escapes
  # - Mergify leverages Python regular expressions to match rules.
  #
  # Semantic commit messages
  # - chore:     updating grunt tasks etc.; no production code change
  # - docs:      changes to the documentation
  # - feat:      feature or story
  # - feature:   new feature or story
  # - fix:       bug fix for the user, not a fix to a build script
  # - idea:      general idea or suggestion
  # - question:  question regarding code
  # - test:      test related changes
  # - wip:       work in progress PR
  # ===============================================================================

  - name: Work in Progress
    conditions:
      - "head~=(?i)^wip" # if the PR branch starts with wip/
    actions:
      label:
        add: ["work-in-progress"]
  - name: Hotfix label
    conditions:
      - "head~=(?i)^hotfix" # if the PR branch starts with hotfix/
    actions:
      label:
        add: ["hot-fix"]
  - name: Bug / Fix label
    conditions:
      - "head~=(?i)^(bug)?fix" # if the PR branch starts with (bug)?fix/
    actions:
      label:
        add: ["bug-P3"]
  - name: Documentation label
    conditions:
      - "head~=(?i)^docs" # if the PR branch starts with docs/
    actions:
      label:
        add: ["documentation"]
  - name: Feature label
    conditions:
      - "head~=(?i)^feat(ure)?" # if the PR branch starts with feat(ure)?/
    actions:
      label:
        add: ["feature"]
  - name: Chore label
    conditions:
      - "head~=(?i)^chore" # if the PR branch starts with chore/
    actions:
      label:
        add: ["update"]
  - name: Question label
    conditions:
      - "head~=(?i)^question" # if the PR branch starts with question/
    actions:
      label:
        add: ["question"]
  - name: Test label
    conditions:
      - "head~=(?i)^test" # if the PR branch starts with test/
    actions:
      label:
        add: ["test"]
  - name: Idea label
    conditions:
      - "head~=(?i)^idea" # if the PR branch starts with idea/
    actions:
      label:
        add: ["idea"]


  # ===============================================================================
  # STALE BRANCHES
  # ===============================================================================

  - name: Close stale pull request
    conditions:
      - base=master
      - -closed
      - updated-at<21 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it's a mistake.
      label:
        add: [ "stale" ]
